feat : 내 카테고리 CRUD API 작성
gusto-umc/Gusto-Server pull request #17
Opened 2024-01-28 13:30 UTC by kchaeeun

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : 
    * 내 카테고리 CRUD API #7
    * 내 카테고리 별 가게 목록 조회 API
- [x] 버그 수정 : @Builder.Default를 사용해 @Builder가 default값을 무시하는 경우 처리
- [x] 리펙토링 : build.gradle에서 security 라이브러리 추가 시 임의로 권한 처리를 요구해 주석 처리
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 작업 내역

- Entity 내 default 값을 요구하는 필드 위의 어노테이션에 @Builder.Default 추가
- builde.gradle `implementation 'org.springframework.boot:spring-boot-starter-security'` 주석 처리

### Issue Number 

close: #7

### 어떤 부분에 리뷰어가 집중하면 좋을까요?
* 많은 내용 수정, 추가로 인해 충돌이 있을 수 있습니다. entity 부분 확인 부탁드립니다!
* 버그 발생 즉시 pr을 날렸어야 하는데 feature 개발 중 오류를 발견해 부득이 하게 한꺼번에 pr를 날리게 되었습니다.

2024-01-28 16:14 UTC, wityoung-h requested changes
수고하셨습니다!
stream 사용 보고 감탄했어요 완전 stream 천재 만재..! 👍

2024-01-28 16:14 UTC, wityoung-h commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +            MyCategory existing = myCategoryOptional.get();
위와 같은 상황에서는 isPresent()를 사용하는 것보다 .orElseThrow() 를 통해 exception를 throw하는 것이 권장되는 것으로 알고 있습니다!

혹시 isPresent()를 사용하신 특별한 이유가 있으실까요? 아래를 보니 `modifyMyCategory` method에서는 orElseThrow()를 사용하셨더라구요!! 둘의 차이를 어떻게 두신 건지 궁금합니다.

2024-01-28 16:20 UTC, wityoung-h reviewed
.

2024-01-28 16:34 UTC, wityoung-h commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +        Optional<MyCategory> myCategoryOptional = myCategoryRepository.findByMyCategoryName(createMyCategoryDTO.getMyCategoryName());
Category이름 중복 체크가 필요한지에 대해서 PM님과 이야기 중에 있습니다!
조정되는 대로 말씀드릴게요~

2024-01-29 04:23 UTC, Hwater00 approved these changes

2024-01-29 08:57 UTC, yujiyea approved these changes
수고하셨습니다!! 혜성님 stream 사용이랑 민니님 리뷰로 많이 배웠습니다.😀

2024-01-29 10:48 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
> +    private final StoreStatus storeStatus = StoreStatus.ACTIVE;
아  @Build.Default 혹은 final을 쓰라고 error 메시지에 떴었는데, @Builder.Default 통일하는 것이 좋을 거 같네요. 수정할게요!

2024-01-29 11:03 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
> +    Optional<MyCategory> findByMyCategoryName(String myCategoryName);
Optional이 nullexception을 방지해주는데 카테고리 생성 시 동일한 이름이 없을 경우가 있을 수 있어 Optional로 null처리를 할 수 있게 사용했습니다! 근데 어차피 else로 null일 경우 처리를 두긴 했어서 큰 의미는 없어 보이긴 하네요.

2024-01-29 11:15 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
앗 맞습니다. 첫번째 말씀의 경우 PR문서에 추가하도록 하겠습니다! 
두번째 경우는 이슈에서 보시다시피 로직이 복잡해 질거 같아 아예 새로운 API로 작업하고 있는데요. 그냥 합쳐서 구현하는게 나을까요?

2024-01-29 11:17 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +            MyCategory existing = myCategoryOptional.get();
아 그렇군요. 존재할때 적어야할 IF문이 많아져서 orElseThrow를 사용하지 않았는데요. 권장되는 것으로 변경해볼게요!

2024-01-29 11:35 UTC, kchaeeun commented
resolve 처리하지 않은 부분은 아직 처리 하지 못했는데, 금요일 전까지는 해결해서 push 날리도록 하겠습니다!

2024-01-29 12:38 UTC, Jeonghee-Han approved these changes
수고하셨습니다😀😀

2024-01-29 13:37 UTC, wityoung-h commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
> +    Optional<MyCategory> findByMyCategoryName(String myCategoryName);
if-else로 null 처리를 하는 것보다 optional 사용이 더 좋다고 알고 있어서 optional로 통일해주시면 좋을 것 같습니다!

2024-01-29 13:38 UTC, wityoung-h commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
아아 그러셨군요! 말씀대로 새로운 API로 작업하시는 게 더 좋을 듯 합니다! 멋져요 👍

2024-01-29 16:03 UTC, wityoung-h commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +        Optional<MyCategory> myCategoryOptional = myCategoryRepository.findByMyCategoryName(createMyCategoryDTO.getMyCategoryName());
해당 부분 그대로 진행해주시면 될 것 같습니다!!!

2024-01-30 12:42 UTC, merged