feat : RestControllor를 이용한 에러 핸들러
gusto-umc/Gusto-Server pull request #25
Opened 2024-01-30 06:17 UTC by yujiyea

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 :
에러 핸들러 생성
- [ ] 버그 수정 :
- [ ] 리펙토링 :
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 작업 내역
예외 발생 시 응답 형태는 아래와 같도록 했습니다. 
```
{ 
  "success": false,
  "errorCode": 4100,
  "message": "잘못된 요청입니다."
}
```
예외 응답은 변경이 필요없기 때문에 record로 만들어서 데이터 가공 시 중간에 변질될 우려가 없도록 했습니다. 

### Issue Number 
연관된 Issue: #19 

### 어떤 부분에 리뷰어가 집중하면 좋을까요?
저희가 응답 형태를 의논하지 않아서 다들 아는 워크북을 기준으로 에러핸들러를 수정해서 만들었습니다. 
하지만,  에러 핸들러를 공부하다보니 정해야하는 부분이 있는 것 같아 노션에 정리해두겠습니다.
노션 문서를 보시고 의견을 주시면 코드를 수정하도록 하겠습니다!

2024-01-30 11:49 UTC, zzo3ozz commented
수고 많으셨습니다!

노션 문서도 확인해봤는데 개인적으로는 ResponseEntity로 Api Response로 감싸서 사용하는 방법이 좋을 것 같아요.
저 역시도 자체 ApiResponse를 사용할 때 Http status는 200인데 response에서는 리턴을 404로 내는 부분이 이해가 잘 되지 않더라구요.

ResponseEntity를 사용하는 경우, 말씀하신대로 응답 성공 시(status 200)에는 기존 ApiResponse의 "result" 부분에 해당하는 부분만 return을 하고, 에러 발생하는 경우 body에 값을 추가하는 편이 좋은 것 같습니다.
다만 에러 발생 시 success 부분은 상태 코드로도 판정이 가능하니 다음과 같이 제외하는 편이 좋지 않을까 싶습니다.
```java
{ 
  "errorCode": 4100,
  "message": "잘못된 요청입니다."
}
```

다른분들도 의견 부탁드립니다~

2024-01-30 11:50 UTC, zzo3ozz reviewed
수고 많으셨습니다!

노션 문서도 확인해봤는데 개인적으로는 ResponseEntity로 Api Response로 감싸서 사용하는 방법이 좋을 것 같아요.
저 역시도 자체 ApiResponse를 사용할 때 Http status는 200인데 response에서는 리턴을 404로 내는 부분이 이해가 잘 되지 않더라구요.

ResponseEntity를 사용하는 경우, 말씀하신대로 응답 성공 시(status 200)에는 기존 ApiResponse의 "result" 부분에 해당하는 부분만 return을 하고, 에러 발생하는 경우 body에 값을 추가하는 편이 좋은 것 같습니다.
다만 에러 발생 시 success 부분은 상태 코드로도 판정이 가능하니 다음과 같이 제외하는 편이 좋지 않을까 싶습니다.
```java
{ 
  "errorCode": 4100,
  "message": "잘못된 요청입니다."
}
```

다른분들도 의견 부탁드립니다~

2024-01-30 16:38 UTC, Jeonghee-Han requested changes
하단의 comment review를 확인해주세요.

2024-01-30 16:39 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
> +public record ExceptionResponse<T>(
`record`를 처음 봐서 한번 찾아보았습니다!

찾아보니 JDK 16부터 정식 스펙으로 포함되었고, 불변 객체를 생성할 수 있는 유형의 클래스라고 합니다.

> - 멤버 변수가 private final로 선언됨
> - 필드별 getter가 자동으로 생성됨
> - 모든 멤버 변수를 인자로 하는 public 생성자(constructor)가 자동으로 생성됨
> - equals, hashcode, toString이 자동으로 생성됨

등의 특징이 있나봅니다!

대체로 DTO 사용시 많이 사용하는 것 같아요! DTO 클래스를 record로 통일해보는 것도 나쁘지 않을 것 같은데 다들 어떠신가요?!

블루 덕분에 하나 배워갑니다! 👍

2024-01-30 16:39 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/global/exception/customException/TempException.java
제가 에러 핸들러 관련 학습이 아직 부족해서 그런데,
혹시 해당 class는 무엇을 위해 구현되었는지 알려주실 수 있을까요?!

2024-01-30 16:42 UTC, Jeonghee-Han approved these changes

2024-01-31 04:44 UTC, yujiyea commented on gusto/src/main/java/com/umc/gusto/global/exception/customException/TempException.java
해당 부분은 테스트 용도로 만든거입니다. 다른 분들이 커스텀 예외처리 만들 때 이렇게 만들면 된다는 예시로 올려두었습니다.

2024-01-31 04:44 UTC, yujiyea commented on gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
> +public record ExceptionResponse<T>(
저는 record로 DTO나 VO를 하는 게 좋다고 생각합니다!!

2024-01-31 06:45 UTC, Hwater00 commented on gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
> +public record ExceptionResponse<T>(
record가 데이터 불변성을 보장해서 DTO에 사용하면 더 안정성 있다고 생각합니다.

2024-01-31 06:47 UTC, Hwater00 approved these changes

2024-01-31 14:43 UTC, merged