Feat/hard delete scheduler
gusto-umc/Gusto-Server pull request #297
Opened 2024-07-22 12:08 UTC by Hwater00

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : 스프링부트 스케줄링을 통한 hard delete 구현
- [ ] 버그 수정 :
- [ ] 리펙토링 :
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 변경사항 및 이유

- 그룹 삭제 로직에서 그룹 INACTIVE 시 그룹 내 루트 INACTIVE 변경 로직 추가

### 작업 내역
- Group Entity  hard delete 시에
- Route Entity   hard delete 시에 
- MyCategory Entity   hard delete 시에 
- Review Entity   hard delete 시에 

### PR 특이 사항

- 부모-자식 연관관계에 따른 스케줄링 순서에 영향을 받음(즉, 자식 삭제 스케줄링 작업 이후 부모 삭제 스케줄링 작업이 진행되야 함)

### Issue Number 

close: #

### 어떤 부분에 리뷰어가 집중하면 좋을까요?
방법1)
현재 ManyToOne 단방향 관계인 연관관계가 있는데 , @OneToMany로 양방향 관계를 추가하고 cascade와 orphanRemoval 설정
-> 현재 Route, myCategory, review-tagging 적용됨

방법2)

2024-07-23 15:35 UTC, kchaeeun approved these changes

2024-07-24 08:10 UTC, yujiyea approved these changes
양방향 관계 설정해서 삭제하는 방식이 좋은 것 같습니다.
직접 하는 것보다는 스프링 부트를 이용하는 것이 안정성 측면에서는 좋을 것 같아요.

2024-07-24 10:53 UTC, zzo3ozz requested changes
수고하셨습니다!

참고로 일반적으로 jpa에서 양방향 매핑보다 단방향 매핑 사용이 많은 이유는
성능적인 이유가 크다고 합니다.

양방향 매핑 시 코드의 복잡성, 추가적인 오버헤드가 발생할 수 있고,
테이블 관계에 따라 직렬화 시 무한 루프가 발생할 수 있다고 합니다.

현재 양방향 매핑이 되어 있고 삭제처리가 되어 있는 내용들을 굳이 단방향 매핑으로 돌릴 필요는 없는 것 같습니다.
단방향 매핑이 되어 있는 테이블들의 FK는 `cascade`, `set null` 옵션을 데이터베이스 FK 자체에 걸어주시면 될 것 같습니다. (방법 2를 채택한 테이블에 대한 이야기 입니다!)
현재 방법1의 삭제 옵션의 경우 jpa의 엔티티 매니저, 즉 캐시에서의 동작을 처리하는 것으로 알고 있습니다. 엔티티 매니저가 아닌 db에서 자동으로 삭제 혹은 set null 처리가 된다면 코드 상으로 삭제 옵션을 명시하지 않아도 문제 없을 것 같습니다~

2024-08-05 11:22 UTC, Hwater00 commented
>  단방향 매핑이 되어 있는 테이블들의 FK는 `cascade`, `set null` 옵션을 데이터베이스 FK 자체에 걸어주시면 될 것 같습니다. (방법 2를 채택한 테이블에 대한 이야기 입니다!) 현재 방법1의 삭제 옵션의 경우 jpa의 엔티티 매니저, 즉 캐시에서의 동작을 처리하는 것으로 알고 있습니다. 엔티티 매니저가 아닌 db에서 자동으로 삭제 혹은 set null 처리가 된다면 코드 상으로 삭제 옵션을 명시하지 않아도 문제 없을 것 같습니다~

ON DELETE SET NULL의 경우, 부모 테이블의 행이 삭제되면 자식 테이블의 관련된 컬럼이 NULL로 설정되어 자식 테이블의 행을 유지하면서, 부모 테이블의 특정 행이 삭제되었음을 반영하는 것이라 casecade만 적용했습니다.

2024-08-05 12:39 UTC, closed without merging