refactor : MyCategory entity / null 처리를 위한 방법 수정 / PRIVATE 경우 카테고리 조회 불가
gusto-umc/Gusto-Server pull request #32
Opened 2024-02-01 09:11 UTC by kchaeeun

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : publishCategory가 PRIVATE인 경우 조회 불가 처리
- [ ] 버그 수정 :
- [x] 리펙토링 : MyCategory entity 수정 / null 처리를 위한 방법 수정
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 변경사항 및 이유

- 지난 #7 pr에 대한 코멘트들을 고려해 로직 일부 수정과 기능 추가가 있습니다.

### 작업 내역

- @Builder.Default 공통 처리 & MyCategory Entity Status 필드 삭제 / @Setter 추가
- isPresent 대신 .orElseThrow()로 null 처리
- Optional 클래스 사용
- 내 카테고리가 private일 경우 조회 불가 처리

close: #26

### 어떤 부분에 리뷰어가 집중하면 좋을까요?
- 리뷰 내용을 수용해 작성한 코드로 크게 달라진 점은 없습니다. 그래도 혹시 몰라 리뷰어 설정을 해두었습니다

2024-02-01 11:05 UTC, zzo3ozz requested changes
꾸준한 PR 넘 멋지십니다 👍 👍 
Exception 관련 코멘트는 필히 확인 부탁드리고,
나머지는 제안 드려본 내용이니 편하신대로 해주심 됩니다..!

2024-02-01 11:05 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("MyCategory with the same name does not exist"));
해당 코드의 경우 중복되는 카테고리 이름이 존재하지 않으면 exception을 발생시키지 않나요..?
중복되는 카테고리 이름이 존재할 때 exception을 발생시켜야 할 것 같습니다..!
(`orElseThrow` 대신 `ifPresent`를 사용하시면 될 것 같아요!)

2024-02-01 11:05 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +            throw new RuntimeException("MyCategory is in ACTIVE");
해당 과정을 생략할 수 있도록 애초에 DB에서 불러올 때 status가 ACTIVE인 myCategory만을 불러오는 것은 어떨까요?!

2024-02-01 11:05 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/global/common/BaseEntity.java
> +@Setter
@Setter 삭제시 해당 파트도 같이 삭제해주시면 될 것 같습니다!

2024-02-01 15:14 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("MyCategory with the same name does not exist"));
띠용 그러게요. 감사합니다 🥹

2024-02-01 15:50 UTC, yujiyea approved these changes

2024-02-02 02:13 UTC, Hwater00 approved these changes

2024-02-02 03:00 UTC, Jeonghee-Han approved these changes

2024-02-02 15:13 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +            throw new RuntimeException("MyCategory is in ACTIVE");
INACTIVE인 경우 새로 카테고리를 생성하는게 아닌 ACTIVE로 바꾸는 과정만 처리하기 위해 DB에서 불러올때 ACTIVE만 불러오면 안될거 같긴한데, 다른 이야기 하시는 걸까요?!

2024-02-03 05:55 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
> +            throw new RuntimeException("MyCategory is in ACTIVE");
전체 회의 때 얘기한 내용 다시한번 정리해두도록 할게요!

그룹명 중복 체크 시 ACTIVE 상태의 데이터만을 대상으로 하여
INACTIVE인 상태의 카테고리와 동일 이름의 카테고리를 생성 시 status를 ACTIVE로 변경하는 것이 아닌
새로운 카테고리를 생성해주시면 됩니당

2024-02-03 15:36 UTC, merged