feat : 엔티티 생성 (MyCategory, Review, User) 및 양방향 처리
gusto-umc/Gusto-Server pull request #6
Opened 2024-01-18 07:28 UTC by kchaeeun

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : MyCategory, Review, User Entity 생성 #5
- [ ] 버그 수정 :
- [ ] 리펙토링 :
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 작업 내역

- HashTag를 여러개 설정 시 중복처리를 막기 위해 Set를 사용해 매핑했습니다.

### PR 특이 사항

- Store과 매핑이 필요한 경우가 있어 민니님의 Store Entity만을 복사해서 가져왔습니다.
- BaseEntity, BaseTime 모두 민니님에게 파일을 받아 사용했습니다.

### Issue Number 

close: #5

### 어떤 부분에 리뷰어가 집중하면 좋을까요?
- Follow Entity의 매핑의 경우 완벽히 이해하지 못한 거 같아 제대로 작성한 것인지 리뷰 부탁드립니다.

2024-01-18 11:18 UTC, zzo3ozz requested changes
수고하셨습니다!! 👍 리뷰 확인해주세요!

2024-01-18 11:18 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/HashTag.java
> +    private Set<Tagging> taggingSet = new HashSet<>();
제 생각엔 HashTag 엔티티에서 Tagging 엔티티를 조회할 일이 없을 것 같은데, 혹시 이 방향의 매핑을 추가한 이유를 알 수 있을까요?

2024-01-18 11:18 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
> +    private Set<Tagging> taggingSet = new HashSet<>();          // 중복 허용x
List 대신 Set을 사용해서 중복 값을 제어할 수 있다는 점은 처음 알았어요 👍 
덕분에 하나 더 알아갑니다!

다만 프론트 로직상 중복 태그가 발생하는 일은 없을 것 같아 List로도 충분할 것 같은데, 다른 분들의 의견은 어떠신지 궁금합니다! 👀
다들 의견 달아주세요!!

2024-01-18 11:18 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
> +
아래의 `@OneToMany` 어노테이션이 적용된 필드들의 경우,
user에서 조회되는 것보다 각각의 엔티티에서 user를 통해 filter를 해서 검색하는 편이 맞을 것 같아요!
이 경우 user 하나를 검색할 때 모든 socialList, followList, reviewList가 불러와지기 때문에 서버에 부하가 상당할 것으로 사료됩니다!

2024-01-18 11:18 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/user/enums/Age.java
`Age`, `Gender`, `MemberStatus`, `SocialStatus`, `SocialType` enum의 경우 각 엔티티 내부에서만 사용하는 enum이기 때문에 엔티티 내부에 enum을 선언하는 것이 더 좋을 것 같습니다!
예시
```java
public class User {
  // ... //
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private Gender gender;
  // ... //
  public enum Gender {
    FEMALE, MALE, NONE;
  }
}
```

2024-01-18 16:47 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
> +    private Set<Tagging> taggingSet = new HashSet<>();          // 중복 허용x
저도 프런트에서 해결된 문제라고 생각했는데, 혹시나 해서 넣어봤습니다. list 사용해도 좋아요!
여기 맡으시는 분이 이해 안갈까봐 단순 주석 처리 해둔 겁니다 👍

2024-01-18 16:50 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
> +
양방향 매핑 선택 아직 어렵긴 해서.. 그럼 myCategoryList를 제외하고 양방향 매핑 처리는 모두 지우도록 해볼게요!
제가 이해한게 맞다면 이모지 부탁드립니다 ! @zzo3ozz

2024-01-18 16:54 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/user/enums/Age.java
엔티티 내부가 너무 복잡해 보여서 enum은 따로 패키지 넣어 두긴 했는데 다른 분들 의견 주시면 민니님과 통일하겠습니다 ! 👯

2024-01-18 17:05 UTC, zzo3ozz commented on gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
> +
앗 myCategoryList를 제가 놓쳤네요! 해당 부분도 같이 삭제되는 게 맞는 듯 합니다!!!!! 👍

2024-01-18 17:07 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/HashTag.java
> +    private Set<Tagging> taggingSet = new HashSet<>();
흠 저도 고민했던 부분인데요. 제 기억으로는 해시태그를 하나만 달기로 했던 거 같은데, 그렇게 되면 Tagging 엔티티가 필요 없다고 생각했어요.

근데 erd를 보니 Tagging 엔티티가 있어서 중복이 되는 건가 싶어 다대다 관계를 맺어야 된다고 생각해서 HashTag와 Review 모두에 매핑을 추가했습니다.

2024-01-18 17:34 UTC, kchaeeun commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/HashTag.java
> +    private Set<Tagging> taggingSet = new HashSet<>();
아.. 제가 잘못 이해하고 있었네요. 그렇다면 민니님 말씀이 맞는 것 같습니다. 많이 배웁니다. 감사합니다 🙇

2024-01-18 18:40 UTC, yujiyea commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
> +    private Set<Tagging> taggingSet = new HashSet<>();          // 중복 허용x
저는 백에서는 데이터 변조를 막는 용도, 프론트에서는 사용자에게 빠른 응답을 줄 수 있도록 하는 용도로 가능하다면 양쪽 다 검사하는 것이 좋다고 생각합니다.

2024-01-18 18:40 UTC, yujiyea commented on gusto/src/main/java/com/umc/gusto/domain/user/enums/Age.java
저도 가독성을 생각해서 entity에 enum클래스를 넣거나 지금처럼 enum폴더를 만들어도 좋은 것 같습니다!

2024-01-19 02:07 UTC, Jeonghee-Han commented on gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
> +    private Set<Tagging> taggingSet = new HashSet<>();          // 중복 허용x
저장되는 데이터의 순서를 보장해야한다면 List를 사용해야겠지만, 그렇지 않은 경우에는 Set의 실행 속도가 매우 빠르기 때문에 탐색이 잦은 경우 Set을 고려해야한다고 생각합니다.

2024-01-19 03:26 UTC, Jeonghee-Han commented on gusto/src/main/java/com/umc/gusto/domain/user/enums/Age.java
엔티티 내부에 enum을 선언하더라도 해당 클래스와 enum을 모두 public으로 선언하면 다른 클래스에서 해당 enum을 재사용할 수 있습니다! 다만, 엔티티 내부에 enum을 선언하면 해당 엔티티 클래스에 강하게 결합되어 있어서 재사용이 제한될 수 있습니다. 

저는 해당 enum의 재사용 가능성이 낮다면, 엔티티 내부에 enum을 선언하여 명시적으로 해당 enum이 엔티티와 강하게 결합되어 있음을 명시적으로 나타내면 좋을 것 같습니다!

2024-01-19 05:32 UTC, zzo3ozz approved these changes
수고하셨습니다~~

2024-01-19 08:34 UTC, merged